yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/',
         views.group_posts,
         name='group_posts'),
    path('profile/<str:username>/',
         views.profile,
         name='profile'),
    path('posts/<int:post_id>/',
         views.post_detail,
         name='post_detail'),
    path('create/', views.post_create,
         name='post_create'),
    path('posts/<int:post_id>/edit/',
         views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView,
                                       LogoutView,
                                       PasswordChangeView,
                                       PasswordChangeDoneView,
                                       PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView)
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    # Смена пароля
    path('password_change/',
         PasswordChangeView
         .as_view(template_name='users/password_change.html'),
         name='password_change'),
    # Сообщение об успешном изменении пароля
    path('password_change/done/',
         PasswordChangeDoneView
         .as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),
    # Восстановление пароля
    path('password_reset/',
         PasswordResetView
         .as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    # Сообщение об отправке ссылки для восстановления пароля
    path('password_reset/done/',
         PasswordResetDoneView
         .as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    # Вход по ссылке для восстановления пароля
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView
         .as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    # Сообщение об успешном восстановлении пароля
    path('reset/done/',
         PasswordResetCompleteView
         .as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth.models import User

length: int = 15


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=255, unique=True, db_index=True,
                            verbose_name="URL", null=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста')
    pub_date = models.DateTimeField('дата публикации', auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='posts_author',
                               verbose_name='Автор'
                               )
    group = models.ForeignKey(Group, on_delete=models.SET_NULL,
                              related_name='posts_group',
                              blank=True, null=True,
                              verbose_name='Группа',
                              help_text='Выберите группу'
                              )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:length]

yatube/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group']
        labels = {
            'text': 'Текст',
            'group': 'Группа',
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Post, Group, User
from .forms import PostForm
from django.shortcuts import redirect
from django.core.paginator import Paginator


text_output: int = 10


def index(request):
    template = 'posts/index.html'
    post_list = Post.objects.all()
    paginator = Paginator(post_list, text_output)
    page_number = request.GET.get('page')
    if(not page_number):
        page_number = 1
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'post_list': post_list,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts_group.all()[:text_output]
    paginator = Paginator(posts, text_output)
    page_number = request.GET.get('page')
    if(not page_number):
        page_number = 1
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'group': group,
        'posts': posts
    }
    return render(request, template, context)


def profile(request, username):
    page_number = request.GET.get('page')
    profile = get_object_or_404(User, username=username)
    post_list = profile.posts_author.all()
    post_count = post_list.count
    paginator = Paginator(post_list, text_output)
    page_obj = paginator.get_page(page_number)
    context = {
        'profile': profile,
        'page_obj': page_obj,
        'paginator': paginator,
        'post_count': post_count
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    context = {
        'post': post
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/post_create.html'
    author = get_object_or_404(User, pk=request.user.id)
    form = PostForm(request.POST or None, initial={'author': author.id})
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect(
            'posts:profile', request.user
        )
    return render(request, template, {'form': form})


@login_required
def post_edit(request, post_id):
    template = 'posts/post_create.html'
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(request.POST or None, instance=post)

    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    return render(request, template,
                  {'form': form, 'is_edit': True, 'post': post}
                  )

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/posts/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
  <h1>Привет, я автор</h1>
  <p>
    Тут я размещу информацию о себе, используя свои умения верстать.
    Картинки, блоки, элементы бустрап. А может быть, просто напишу несколько абзацев текста. 
  </p>
{% endblock %} 

yatube/posts/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
  <div class="row">
    <h1>Вот что я умею</h1>
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Python
        </li>
        <li class="list-group-item">
          Django
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>Текст страницы "Технологии"</p>
    </article>
  </div>
{% endblock %} 

yatube/posts/templates/base.html
{% load static %}
<!DOCTYPE html> 
<html lang="ru"> 
  <head>
    <link rel="stylesheet" href="{% static 'css/style.css'%}" type="text/css">
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" type="text/css">
    <title>
      {% block title %}
      {% endblock %}
    </title>
  </head>
  <body>
    {% include "includes/header.html"%}
     <main> 
       <div class="container py-5">
        <h1>{% block header %}
        {% endblock %}</h1>
         {% block content %}
           Информация на главной странице будет тут. 
         {% endblock %}
       </div>   
     </main>   
    {% include "includes/footer.html"%}
  </body>
</html>

yatube/posts/templates/includes/footer.html
{% load static %}
<footer class="page-footer font-small blue border-top">
  <div class="footer-copyright text-center py-3">
    © {{ year }} Copyright 
    <p>
      <span style="color:red">Ya</span>tube
    </p> 
  </div>    
</footer>

yatube/posts/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
  <header>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: lightskyblue">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        &nbsp;&nbsp;&nbsp;<img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="nav nav-pills ms-auto">
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" href="{% url 'about:author' %}">Об авторе</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" href="{% url 'about:tech' %}">Технологии</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}" href="{% url 'posts:post_create' %}">Новая запись</a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light {% if view_name  == 'users:password_change' %}active{% endif %}" href="{% url 'users:password_change' %}">Изменить пароль</a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}" href="{% url 'users:logout' %}">Выйти</a>
            </li>     
            <li class="nav-link link-dark">
              Пользователь: <b>{{ user.username }}</b>
            </li>
            </ul>
          {% else %}
            <li class="nav-item">
              <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}" href="{% url 'users:login' %}">Войти</a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}" href="{% url 'users:signup' %}">Регистрация</a>
            </li>
            </ul>
          {% endif %}
      </div>
    </nav>
  </header>
{% endwith %}

yatube/posts/templates/includes/post_card.html
{% load static %}
<ul>
  <li>
    Автор: {{ post.author.get_full_name }}
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
</ul>
<p>{{ post.text }}</p>

yatube/posts/templates/includes/profile_post_card.html
{% load static %}
<article>
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
      <a href="<!-- -->">все посты пользователя</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
</article>   

yatube/posts/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block header %}
  {{ group.title }}
{% endblock %}
{% block content %}
  <p>{{ group.description }}</p>
  {% for post in posts %}
    {% include "includes/post_card.html"%}   
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %} 
  {% include 'posts/includes/paginator.html' %} 
{% endblock %}

yatube/posts/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Предыдущая
          </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Следующая
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}    
    </ul>
  </nav>
{% endif %}

yatube/posts/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
 <h1>Последние обновления на сайте</h1>
  {% for post in page_obj %}
    {% include "includes/post_card.html"%}
    {% url 'posts:group_posts' post.group.slug as the_url %}
    {% if the_url %}
      <a href="{{ the_url }}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %} 
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/posts/templates/posts/post_create.html
{% extends "base.html" %}
{% block title %}
  {% if is_edit %}
    Сохранить запись
  {% else %}
    Добавить запись
  {% endif %}  
{% endblock %}
{% load user_filters %}
{% block content %} 
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if is_edit %}
              Сохранить запись
            {% else %}
              Добавить запись
            {% endif %}             
          </div>
          <div class="card-body">
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                  </div>
                {% endfor %}
              {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
              </div>
            {% endfor %}
          {% endif %}
          {% if is_edit %}
            <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_edit' post.pk %}">
          {% else %}
            <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create' %}">
          {% endif %}  
            {% csrf_token %}
              {% for field in form.visible_fields %}
              <div class="form-group row my-3 p-3 textarea">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>    
                {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
              {% endfor %}
              {% for field in form.hidden_fields %}
              <div class="form-group row my-3 p-3 textarea">
                {{ field|addclass:'form-control' }}
              </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}  
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/posts/templates/posts/post_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %} <title>Пост {{post.text|truncatechars:30 }}</title> {% endblock %}
{% block content %}
  <body>       
    <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}
              <li class="list-group-item">
                Группа: {{ group.name }}
                <a href="{% url 'posts:group_posts' post.group.slug %}">
                  все записи группы
                </a>
              </li>
            {% endif %}
              <li class="list-group-item">
                Автор: {{ post.author.get_full_name }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                Всего постов автора:  <span >{{ post_count }}</span>
              </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author%}">
                все посты пользователя
              </a>
            </li>
            {% if user == post.author %}
            <a class="btn btn-default" href="{% url 'posts:post_edit' post_id=post.pk %}"><span class="list-group-item">
              Редактировать запись</span></a>
          </ul>
          {% endif %}
        </aside>
        <article class="col-12 col-md-9">
          <p>
            {{ posts.text }}
          </p>
          <p class="col-12 col-md-3">
          </p>
        </article>
      </div> 
    </main>
  </body>
  {% endblock %}

yatube/posts/templates/posts/profile.html
<!DOCTYPE html>
<html lang="ru"> 
  <head>  
    <title>Профайл пользователя</title>
  </head>
  <body>       
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="/">
            <img src="/static/img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>
        </div>
      </nav>      
    </header>
    <main>
      <div class="container py-5">        
        <h1>Все посты пользователя</h1>
        <h3>Всего постов: {{ post_count}} </h3>
        {% for post in page_obj %}
          {% include "includes/profile_post_card.html"%}
          {% url 'posts:group_posts' post.group.slug as the_url %}
          {% if the_url %}
            <a href="{{ the_url }}">все записи группы</a>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %} 
        {% include 'posts/includes/paginator.html' %} 
      </div>
    </main>
    <footer class="border-top text-center py-3">
      <p>© Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>

yatube/posts/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

yatube/posts/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет -->
            <a href="{% url 'users:password_reset' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

yatube/posts/templates/users/password_change.html
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <title>Изменение пароля</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Изменить пароль
              </div>
              <div class="card-body">
                <form method="post" action="{% url 'users:password_change' %}">
                  {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_old_password">
                      Старый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                      <small id="id_new_password1-help" class="form-text text-muted">
                        <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                      </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Изменить пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
    </main>
	  <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>

yatube/posts/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %} 